-- Create db
CREATE database music_shop;


-- Create table
CREATE table music_shop.lab_3_music_shop(
OrderID int,
OrderDate varchar(30),
CustID int,
CustName varchar (30),
CustEmail nvarchar (255),
CustCity nvarchar(50),
CustState char(2),
CustZip int,
ProductID int,
ProductName nvarchar(50),
Category varchar (30),
CategoryMgr varchar (30),
Qty int,
UnitPrice decimal(10,2),
LineTotal decimal(10,2));


-- Load data
LOAD data
infile 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/lab3_data.csv'
into table music_shop.lab_3_music_shop
columns terminated by ','
ignore 1 lines;


-- Update date column
UPDATE music_shop.lab_3_music_shop SET OrderDate = STR_TO_DATE(OrderDate, '%m/%d/%y');
ALTER TABLE music_shop.lab_3_music_shop MODIFY OrderDate DATE;

-- Script from EDR model
-- MySQL Script generated by MySQL Workbench
-- Sun Jul  5 18:20:12 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema music_shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema music_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `music_shop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `music_shop` ;

-- -----------------------------------------------------
-- Table `music_shop`.`music_shop_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_shop`.`music_shop_product` (
  `ProductID` INT NOT NULL,
  `ProductName` VARCHAR(50) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `Category` VARCHAR(30) NULL DEFAULT NULL,
  `CategoryMgr` VARCHAR(30) NULL DEFAULT NULL,
  `UnitPrice` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`ProductID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `music_shop`.`music_shop_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_shop`.`music_shop_customer` (
  `CustID` INT NOT NULL,
  `CustName` VARCHAR(30) NULL DEFAULT NULL,
  `CustEmail` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `CustCity` VARCHAR(50) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `CustState` CHAR(2) NULL DEFAULT NULL,
  `CustZip` INT NULL DEFAULT NULL,
  PRIMARY KEY (`CustID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `music_shop`.`music_shop_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_shop`.`music_shop_order` (
  `OrderID` INT NOT NULL,
  `OrderDate` DATE NULL DEFAULT NULL,
  `CustID` INT NULL DEFAULT NULL,
  `ProductID` INT NULL DEFAULT NULL,
  `Qty` INT NULL DEFAULT NULL,
  `LineTotal` DECIMAL(10,2) NULL DEFAULT NULL,
  CONSTRAINT `fk_music_shop_order_music_shop_product`
    FOREIGN KEY (`ProductID`)
    REFERENCES `music_shop`.`music_shop_product` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_music_shop_order_music_shop_customer1`
    FOREIGN KEY (`CustID`)
    REFERENCES `music_shop`.`music_shop_customer` (`CustID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- Copy info from original table
insert into music_shop_customer(CustID, CustName, CustEmail, CustCity, CustState, CustZip)
select distinct CustID, CustName, CustEmail, CustCity, CustState, CustZip
from lab_3_music_shop;

insert into music_shop_product(ProductID, ProductName, Category, CategoryMgr, UnitPrice)
select distinct ProductID, ProductName, Category, CategoryMgr, UnitPrice
from lab_3_music_shop;

insert into music_shop_order(OrderID, OrderDate, CustID, ProductID, Qty, LineTotal)
select OrderID, OrderDate, CustID, ProductID, Qty, LineTotal
from lab_3_music_shop;


-- Customer name to first and last name
alter table music_shop_customer
add column CustFirstName varchar(50),
add column CustLastName varchar(50);

update music_shop_customer
set CustFirstName = substring_index(CustName, ' ', 1),
CustLastName = substring_index(CustName, ' ', -1);

alter table music_shop_customer drop column CustName